### ISSUE TITLE
Python hooks handler command not found issue

### ISSUE THREAD

**Issue by dkder3k** [apiaryio/dredd-hooks-python#44] opened 2018-03-28 11:06 UTC
Hi everyone.
Today I have installed dredd_hooks using pip and when I was trying to run dredd with hooks I got:
```
info: Configuration './dredd.yml' found, ignoring other arguments.                                                                                                      
info: Beginning Dredd testing...
info: Found Hookfiles: 0=/home/user/Desktop/dredd_tests/hooks.py
error:
Python hooks handler command not found: dredd-hooks-python
Install python hooks handler by running:
$ pip install dredd_hooks
```

After I removed the package and again install it from sources using `python setup.py install` all works as expected.
I'm using:
Python 3.6.3
dredd v5.1.5
Ubuntu Linux 4.13.0-37-generic; x64

**Comment by w-vi** [comment] 2018-03-28 13:59
Thanks a lot for filing the issue I'll have a look.

**Comment by w-vi** [comment] 2018-03-29 07:50
I've tried it to reproduce on couple of systems and failed so I am not sure if it was just a blip on your system or a more widespread problem. I'll keep it open fo other to see and comment if they encounter it too.

**Comment by dkder3k** [comment] 2018-03-29 08:39
Ok, thanks. I will try to investigate the issue too, if I find something I will let you know.

**Comment by sharkykh** [comment] 2018-04-07 22:53
@w-vi 
The version (0.1.3) on PyPI is from March 8, **2017**.
When installing the package from source (from this repo), the issue is fixed (fixed by @medariox #40 + #41). Please consider pushing a new version to PyPI as soon as possible.

Thanks in advance!

P.S. @dkder3k - FYI. Maybe this will fix it for you too.
Installing from source:
Run (preferably in the Python folder):
`pip install -e git+https://github.com/apiaryio/dredd-hooks-python@master#egg=dredd_hooks`

**Comment by w-vi** [comment] 2018-04-08 08:44
@sharkykh I will release soon, very likely on Monday as I was waiting for the #45 to be merged.

**Comment by w-vi** [comment] 2018-04-09 12:34
Released 0.2.0, @dkder3k Can you try to `pip install` it and see if the issue persists?

**Comment by dkder3k** [comment] 2018-04-09 15:31
@w-vi all works fine, thank you

**Comment by w-vi** [comment] 2018-04-10 06:01
Glad to hear it is fixed, so closing

**Closed by w-vi** 2018-04-10 06:01 UTC
Labels: bug
